### PR TITLE
Add annotations

### PR DESCRIPTION
**Pull request by BoboTiG**
A big add, but again I let you choose if it deserves to be listed on the website.

### CODE REVIEW

**Comment by kichik** [comment]
Definitely a good idea to have, but maybe we can also show how this can be used? A link to [mypy](http://mypy-lang.org/) could probably help too. What do you think the best way to do that would be?

**Comment by BoboTiG** [comment]
Initiially I tried to add a complete example on repl.it, but as we need shell command to launch mypy, it was too rough. If you have an idea, do not hesitate.

**Comment by kichik** [comment]
Maybe we could `print(my_add.__annotations__)` and add a link to mypy in the comments. That should be a good start.

**Comment by kichik** [comment]
Thanks!

**Pull request merged**
